variables:
    AWS_DEFAULT_REGION: us-east-2	

stages:
    - staging
    - deployment

#Production stage
staging:   
    stage: staging  
    image: python:3.6 
    before_script:
    # run tests
    - cd backend/
    - make install
    - cd ..
    # generate ssh key   
    - mkdir -p ~/.ssh     
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
    - chmod 600 ~/.ssh/id_rsa     
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'   
    script:   
    - pwd
    - ls -al
    - bash .gitlab-stage.sh   
    # after_script:
    # - pwd
    # - cd backend
    # - chmod 774 datasets/python_utils/*
    # - ls -al datasets/python_utils/
    # - make test
    # - echo "all tests passed!"
    only:
    - deployment
    #environment:     
    #   name: production     
    #   url: https://your.url.com   
    when: manual

deploy:
    stage: deployment
    # image: alpine
    before_script: 
    #generate ssh key   
    - mkdir -p ~/.ssh     
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
    - chmod 600 ~/.ssh/id_rsa     
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'   
    script:     
    - bash .gitlab-deploy.sh   
    only:
    - deployment