variables:
    AWS_DEFAULT_REGION: us-east-2	

stages:
    - staging
    - deployment

#Production stage
staging:   
    stage: staging  
    image: python:3.6 
    before_script: 
    #generate ssh key   
    - mkdir -p ~/.ssh     
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
    - chmod 600 ~/.ssh/id_rsa     
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'   
    script:     
    - bash .gitlab-stage.sh   
    only:
    - deployment
    #environment:     
    #   name: production     
    #   url: https://your.url.com   
    when: manual

deploy:
    stage: deployment
    #image: python:3.6
    before_script: 
    #generate ssh key   
    - mkdir -p ~/.ssh     
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
    - chmod 600 ~/.ssh/id_rsa     
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'   
    script:     
    - bash .gitlab-deploy.sh   
    #- pip install awscli
    #- aws s3 cp ./static/ s3://fightpoverty.online/ --recursive     # copy all website files into the S3 bucket
    #- aws s3 cp ./api/index.html s3://api.fightpoverty.online/      # copy the api html file to its respective bucket
    #- aws s3 cp ./datasets/ s3://api.fightpoverty.online/ --recursive --exclude "*" --include "*.json"      # copy json datasets into api bucket
    only:
    - deployment