variables:
    AWS_DEFAULT_REGION: us-east-2	
deploy:
    image: python:3.6
    script:
    - pip install awscli
    - aws s3 cp ./static/ s3://fightpoverty.online/ --recursive     # copy all website files into the S3 bucket
    - aws s3 cp ./api/index.html s3://api.fightpoverty.online/      # copy the api html file to its respective bucket
    - aws s3 cp ./datasets/ s3://api.fightpoverty.online/ --recursive --exclude "*" --include "*.json"      # copy json datasets into api bucket
    - which aws
    only:
    - deployment