export const charityImages = {
    "Los Angeles Regional Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Los Angeles Regional Food Bank.jpg", 
    "Stephen Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Stephen Center.jpg", 
    "Peoria Rescue Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Peoria Rescue Ministries.png", 
    " Sacramento": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Sacramento.jpg", 
    "Partnership for the Homeless": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Partnership for the Homeless.jpeg", 
    "Loaves and Fishes": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Loaves and Fishes.jpg", 
    "DuPage PADS": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/DuPage PADS.jpg", 
    "N Street Village": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/N Street Village.jpg", 
    "Dallas Life Foundation": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Dallas Life Foundation.jpg", 
    "Thermal Belt Outreach Ministry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Thermal Belt Outreach Ministry.png", 
    "Safe Haven Family Shelter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Safe Haven Family Shelter.png", 
    "Wichita Falls Area Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Wichita Falls Area Food Bank.jpg", 
    "Horizon House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Horizon House.jpg", 
    "Care and Share Food Bank for Southern Colorado": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Care and Share Food Bank for Southern Colorado.jpg", 
    "Eastern Illinois Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Eastern Illinois Foodbank.png", 
    " NJ": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ NJ.png", 
    "Star of Hope Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Star of Hope Mission.gif", 
    "Christ House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Christ House.jpg", 
    "Channel One Regional Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Channel One Regional Food Bank.png", 
    "Jubilee Housing": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Jubilee Housing.jpg", 
    "St. Francis Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/St. Francis Center.jpg", 
    "The Billings Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Billings Food Bank.jpg", 
    "Second Harvest Heartland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Heartland.svg", 
    "Marion Polk Food Share": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Marion Polk Food Share.jpg", 
    "Coalition for the Homeless": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Coalition for the Homeless.jpg", 
    "Community Action House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community Action House.jpg", 
    "Roadrunner Food Bank of New Mexico": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Roadrunner Food Bank of New Mexico.jpg", 
    "Open Doors Kalamazoo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Open Doors Kalamazoo.jpg", 
    "Eugene Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Eugene Mission.jpg", 
    "Bridges Outreach": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bridges Outreach.jpeg", 
    "Hope Clinic": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hope Clinic.jpg", 
    "St. Francis House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/St. Francis House.jpg", 
    " Connecticut": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Connecticut.jpg", 
    "Springfield Victory Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Springfield Victory Mission.png", 
    "Calvary Women's Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Calvary Women's Services.jpg", 
    "Food Bank For New York City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank For New York City.jpg", 
    " Florida": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Florida.jpg", 
    "Bay Area Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bay Area Rescue Mission.jpg", 
    "Springfield Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Springfield Rescue Mission.jpg", 
    "Hunger Network of Greater Cleveland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hunger Network of Greater Cleveland.jpg", 
    "Utah Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Utah Food Bank.png", 
    "Clara White Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Clara White Mission.jpg", 
    " Inc.": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Inc..jpg", 
    "Miriam's Kitchen": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Miriam's Kitchen.png", 
    "Warren Family Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Warren Family Mission.jpg", 
    "CHUM": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/CHUM.jpg", 
    "Rock River Valley Pantry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rock River Valley Pantry.jpg", 
    "Feed My People": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feed My People.jpg", 
    "Shreveport-Bossier Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Shreveport-Bossier Rescue Mission.jpg", 
    "Lakeview Pantry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Lakeview Pantry.jpg", 
    "Transitions Homeless Recovery Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Transitions Homeless Recovery Center.png", 
    "River City Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/River City Food Bank.jpg", 
    "Bridging": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bridging.jpeg", 
    "Save the Family": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Save the Family.jpg", 
    "Charlotte Family Housing": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Charlotte Family Housing.png", 
    "Metrocrest Social Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Metrocrest Social Services.jpg", 
    "Restore Hope Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Restore Hope Ministries.jpg", 
    "Women's Lunch Place": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Women's Lunch Place.jpg", 
    "Lighthouse Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Lighthouse Ministries.jpg", 
    "Orlando Union Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Orlando Union Rescue Mission.jpg", 
    "Hesed House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hesed House.jpg", 
    "Tedford Housing": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Tedford Housing.jpg", 
    "Fairhaven Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Fairhaven Rescue Mission.jpg", 
    "Gateway180 :: Homelessness Reversed": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Gateway180 :: Homelessness Reversed.jpg", 
    "Greater Pittsburgh Community Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Greater Pittsburgh Community Food Bank.jpg", 
    "Maryland Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Maryland Food Bank.png", 
    "New York City Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/New York City Rescue Mission.jpg", 
    "Central Illinois Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Central Illinois Foodbank.jpg", 
    "Carriage Town Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Carriage Town Ministries.jpg", 
    "Chapman Partnership": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Chapman Partnership.jpg", 
    "Greater Cleveland Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Greater Cleveland Food Bank.png", 
    "Rescue Mission Alliance": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rescue Mission Alliance.jpg", 
    "Valley Interfaith Community Resource Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Valley Interfaith Community Resource Center.jpg", 
    "The Food Bank of Lower Fairfield County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Food Bank of Lower Fairfield County.jpg", 
    "Feeding South Florida": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding South Florida.jpg", 
    "God's Pantry Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/God's Pantry Food Bank.jpg", 
    "The INN": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The INN.jpg", 
    "Gateway Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Gateway Rescue Mission.jpg", 
    "Feeding Westchester": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding Westchester.jpg", 
    "The Food Bank of the Golden Crescent": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Food Bank of the Golden Crescent.jpg", 
    "Winston-Salem Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Winston-Salem Rescue Mission.jpg", 
    " Tacoma": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Tacoma.jpg", 
    "Northwest Arkansas Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Northwest Arkansas Food Bank.jpg", 
    "Sunday Breakfast Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sunday Breakfast Rescue Mission.jpg", 
    "Knox Area Rescue Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Knox Area Rescue Ministries.png", 
    "Hunger Task Force": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hunger Task Force.jpg", 
    "Feeding Tampa Bay": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding Tampa Bay.jpg", 
    "St. Vincent de Paul Village": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/St. Vincent de Paul Village.jpg", 
    "Open Door Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Open Door Ministries.jpg", 
    "Harvest Hope Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Harvest Hope Food Bank.jpg", 
    "Los Angeles Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Los Angeles Mission.jpg", 
    "Home Sweet Home Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Home Sweet Home Ministries.jpg", 
    "JOIN": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/JOIN.jpg", 
    "Second Harvest Food Bank of Northwest Pennsylvania": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Northwest Pennsylvania.png", 
    "Martha O'Bryan Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Martha O'Bryan Center.jpg", 
    "Interfaith Works": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Interfaith Works.jpg", 
    "The Greater Boston Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Greater Boston Food Bank.png", 
    "Four States Christian Missions": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Four States Christian Missions.jpg", 
    "West Suburban Community Pantry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/West Suburban Community Pantry.jpg", 
    " Iowa": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Iowa.jpg", 
    "People's City Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/People's City Mission.jpg", 
    "SAMMinistries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/SAMMinistries.jpg", 
    "Western Carolina Rescue Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Western Carolina Rescue Ministries.jpg", 
    "Northlands Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Northlands Rescue Mission.jpg", 
    "Cary Christian Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Cary Christian Center.jpg", 
    "All Faiths Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/All Faiths Food Bank.jpg", 
    "Reconciliation Outreach": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Reconciliation Outreach.jpg", 
    "Union Station Homeless Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Union Station Homeless Services.png", 
    "Mid-South Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Mid-South Food Bank.jpg", 
    "Oliver Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Oliver Gospel Mission.jpg", 
    "HomeFront": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/HomeFront.jpg", 
    "Downtown Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Downtown Rescue Mission.jpg", 
    "Sarah's Circle": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sarah's Circle.jpg", 
    "Volunteers Enlisted to Assist People": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Volunteers Enlisted to Assist People.webp", 
    "Flathead Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Flathead Food Bank.png", 
    "Wheeler Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Wheeler Mission.jpg", 
    "Mercy's Gate": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Mercy's Gate.jpg", 
    "FoodLink for Tulare County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/FoodLink for Tulare County.jpg", 
    "Harvesters: The Community Food Network": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Harvesters: The Community Food Network.jpg", 
    "Community Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community Food Bank.jpeg", 
    "FOOD Share": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/FOOD Share.png", 
    "City Rescue Mission of Saginaw": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/City Rescue Mission of Saginaw.png", 
    "Elk Grove Food Bank Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Elk Grove Food Bank Services.jpeg", 
    "Chattanooga Area Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Chattanooga Area Food Bank.png", 
    "SeaShare": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/SeaShare.png", 
    "Regional Food Bank of Oklahoma": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Regional Food Bank of Oklahoma.png", 
    "Feeding America's Hungry Children": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding America's Hungry Children.jpg", 
    "Second Harvest Food Bank of East Tennessee": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of East Tennessee.jpg", 
    "FeedMore": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/FeedMore.png", 
    "Second Harvest Food Bank of Metrolina": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Metrolina.jpg", 
    "Foodbank of Southeastern Virginia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Foodbank of Southeastern Virginia.jpg", 
    "Food Bank of the Rockies": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of the Rockies.jpg", 
    "South Plains Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/South Plains Food Bank.png", 
    "Good Shepherd Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Good Shepherd Center.jpg", 
    "Middleton Outreach Ministry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Middleton Outreach Ministry.jpg", 
    "Charlotte Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Charlotte Rescue Mission.jpg", 
    "National Alliance to End Homelessness": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/National Alliance to End Homelessness.png", 
    "Vermont Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Vermont Foodbank.jpg", 
    "Panama City Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Panama City Rescue Mission.jpg", 
    "Food Bank of Delaware": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Delaware.jpg", 
    "City Union Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/City Union Mission.png", 
    "Food Bank of Northern Nevada": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Northern Nevada.png", 
    "York Union Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/York Union Rescue Mission.png", 
    "Christian Community Action": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Christian Community Action.jpg", 
    "Manos De Cristo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Manos De Cristo.jpg", 
    "Manna Food Pantries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Manna Food Pantries.jpg", 
    "Homeless Connections": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Homeless Connections.jpg", 
    "Greensboro Urban Ministry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Greensboro Urban Ministry.jpg", 
    "Central Texas Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Central Texas Food Bank.jpg", 
    "Bridgeport Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bridgeport Rescue Mission.jpg", 
    "Ballard Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Ballard Food Bank.jpg", 
    "Shepherd's Table": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Shepherd's Table.jpeg", 
    "West Seattle Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/West Seattle Food Bank.jpg", 
    "Island Harvest": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Island Harvest.jpg", 
    "Guiding Light Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Guiding Light Mission.png", 
    "Community Food Bank of Southern Arizona": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community Food Bank of Southern Arizona.jpg", 
    "The Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Rescue Mission.svg", 
    "The Society of St. Andrew": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Society of St. Andrew.jpg", 
    "Franciscan Outreach": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Franciscan Outreach.png", 
    "Project HOME": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Project HOME.jpg", 
    "Jackson Interfaith Shelter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Jackson Interfaith Shelter.jpg", 
    "Kansas Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Kansas Food Bank.jpg", 
    "Capital Area Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Capital Area Food Bank.png", 
    "Food Lifeline": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Lifeline.gif", 
    "Circle Of Concern": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Circle Of Concern.jpg", 
    "Food Bank of Northwest Indiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Northwest Indiana.jpeg", 
    "Rotary First Harvest": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rotary First Harvest.jpg", 
    "Greater Berks Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Greater Berks Food Bank.png", 
    "SOME": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/SOME.jpg", 
    "MUST Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/MUST Ministries.jpg", 
    "Interfaith Food Pantry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Interfaith Food Pantry.jpg", 
    "Sheffield Place": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sheffield Place.jpg", 
    "Food for Others": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food for Others.jpg", 
    "Virginia Peninsula Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Virginia Peninsula Foodbank.jpg", 
    "The CornerStone Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The CornerStone Rescue Mission.jpg", 
    "Food Finders Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Finders Food Bank.jpg", 
    "Chicago Coalition for the Homeless": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Chicago Coalition for the Homeless.png", 
    "Ozarks Food Harvest": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Ozarks Food Harvest.jpeg", 
    "Food Bank of Central New York": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Central New York.png", 
    "Our House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Our House.gif", 
    "San Antonio Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/San Antonio Food Bank.jpg", 
    "Food Bank of the Albemarle": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of the Albemarle.jpg", 
    "Second Harvest Food Bank of North Central Ohio": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of North Central Ohio.jpg", 
    "Westmoreland County Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Westmoreland County Food Bank.png", 
    "Light of Life Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Light of Life Rescue Mission.png", 
    "Houston Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Houston Food Bank.jpeg", 
    "Presbyterian Night Shelter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Presbyterian Night Shelter.png", 
    "Community Harvest Food Bank of Northeast Indiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community Harvest Food Bank of Northeast Indiana.jpeg", 
    " Denver": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Denver.jpg", 
    "Rescue Mission of Middle Georgia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rescue Mission of Middle Georgia.jpg", 
    "East Texas Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/East Texas Food Bank.jpg", 
    "Community LINC": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community LINC.png", 
    "Larkin Street Youth Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Larkin Street Youth Services.png", 
    "Sunshine Division Portland Police Dept": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sunshine Division Portland Police Dept.jpg", 
    "Back on My Feet": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Back on My Feet.jpg", 
    "Operation Food Search": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Operation Food Search.jpg", 
    "Tri-City Union Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Tri-City Union Gospel Mission.png", 
    "Old Savannah City Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Old Savannah City Mission.jpg", 
    "Northern Illinois Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Northern Illinois Food Bank.jpg", 
    "City Harvest": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/City Harvest.png", 
    "ForKids": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ForKids.jpg", 
    "Food Bank of South Jersey": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of South Jersey.png", 
    "United Food Bank and Services of Plant City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/United Food Bank and Services of Plant City.jpg", 
    "Oregon Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Oregon Food Bank.png", 
    "Sulzbacher Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sulzbacher Center.jpg", 
    "New Horizons": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/New Horizons.jpg", 
    "Deborah's Place": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Deborah's Place.png", 
    "Volunteer Ministry Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Volunteer Ministry Center.png", 
    "reStart": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/reStart.jpg", 
    "Target Hunger": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Target Hunger.jpg", 
    "Primavera Foundation": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Primavera Foundation.png", 
    "Ministry With Community": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Ministry With Community.jpg", 
    "The Redwood Empire Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Redwood Empire Food Bank.jpg", 
    "Second Harvest Northern Lakes Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Northern Lakes Food Bank.jpg", 
    "Feeding America Eastern Wisconsin": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding America Eastern Wisconsin.png", 
    "Second Harvest Foodbank of Southern Wisconsin": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Foodbank of Southern Wisconsin.png", 
    "Long Island Cares": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Long Island Cares.jpg", 
    "Pine Street Inn": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Pine Street Inn.jpg", 
    "Colonial Heights Food Pantry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Colonial Heights Food Pantry.jpg", 
    "Whosoever Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Whosoever Gospel Mission.jpg", 
    "Hope Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hope Ministries.jpeg", 
    "St. Louis Area Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/St. Louis Area Foodbank.jpg", 
    "Jon Bon Jovi Soul Foundation": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Jon Bon Jovi Soul Foundation.jpg", 
    "Hiway 80 Rescue Mission Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hiway 80 Rescue Mission Ministries.jpg", 
    "Open Door Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Open Door Mission.jpg", 
    "Kalamazoo Loaves & Fishes": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Kalamazoo Loaves & Fishes.jpg", 
    "Food Bank of Lincoln": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Lincoln.png", 
    "The Food Bank of Western Massachusetts": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Food Bank of Western Massachusetts.jpeg", 
    "Bridge House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bridge House.jpg", 
    "Rowan Helping Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rowan Helping Ministries.jpg", 
    "Coalition for the Homeless of Central Florida": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Coalition for the Homeless of Central Florida.jpg", 
    "Abode Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Abode Services.jpg", 
    "Rhode Island Community Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rhode Island Community Food Bank.png", 
    "Food Bank of Alaska": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Alaska.jpg", 
    "Bridge Communities": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bridge Communities.jpg", 
    "Nicholas House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Nicholas House.jpg", 
    "The Homeless Families Foundation": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Homeless Families Foundation.jpg", 
    "Greater Chicago Food Depository": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Greater Chicago Food Depository.jpg", 
    "Memphis Union Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Memphis Union Mission.jpg", 
    "Food Bank of Northeast Louisiana Inc": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Northeast Louisiana Inc.jpg", 
    "Heartland Hope Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Heartland Hope Mission.jpg", 
    "The Action Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Action Center.jpeg", 
    "Lotus House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Lotus House.jpeg", 
    "The Food Depot": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Food Depot.png", 
    "Samaritan Inns": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Samaritan Inns.jpg", 
    "Idaho Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Idaho Foodbank.jpg", 
    "John 3:16 Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/John 3:16 Mission.jpg", 
    "Everett Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Everett Gospel Mission.jpg", 
    "Great Falls Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Great Falls Rescue Mission.jpg", 
    "Long Beach Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Long Beach Rescue Mission.png", 
    "STEP": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/STEP.jpg", 
    " NFP": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ NFP.png", 
    "Association of Gospel Rescue Missions": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Association of Gospel Rescue Missions.png", 
    "Healthcare for the Homeless": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Healthcare for the Homeless.png", 
    "Food Bank Coalition of San Luis Obispo County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank Coalition of San Luis Obispo County.png", 
    "Family Promise of Greater Cleveland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Family Promise of Greater Cleveland.gif", 
    "Tarrant Area Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Tarrant Area Food Bank.jpg", 
    "Union Gospel Mission of Tarrant County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Union Gospel Mission of Tarrant County.jpg", 
    "Frisco Family Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Frisco Family Services.png", 
    "City Mission of Schenectady": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/City Mission of Schenectady.jpg", 
    "Food Bank of Eastern Michigan": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Eastern Michigan.jpg", 
    "Community FoodBank of New Jersey": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community FoodBank of New Jersey.png", 
    "Blue Ridge Area Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Blue Ridge Area Food Bank.png", 
    "The Rescue Mission of the Mahoning Valley": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Rescue Mission of the Mahoning Valley.jpg", 
    "PADS Lake County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/PADS Lake County.jpg", 
    "Sharing and Caring Hands": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sharing and Caring Hands.jpg", 
    "Boston Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Boston Rescue Mission.jpg", 
    "Southeast Missouri Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Southeast Missouri Food Bank.jpg", 
    "Rescue Mission of Roanoke": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rescue Mission of Roanoke.jpg", 
    "Union Mission Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Union Mission Ministries.jpg", 
    "CaringWorks": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/CaringWorks.png", 
    "Farmers and Hunters Feeding the Hungry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Farmers and Hunters Feeding the Hungry.gif", 
    "Santa Barbara Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Santa Barbara Rescue Mission.jpg", 
    "Harvest Texarkana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Harvest Texarkana.jpg", 
    "Paul's Place": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Paul's Place.jpg", 
    " Texas": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Texas.png", 
    "The Bowery Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Bowery Mission.jpg", 
    "Committee on Temporary Shelter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Committee on Temporary Shelter.jpg", 
    "Orange County Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Orange County Rescue Mission.jpg", 
    "National Law Center on Homelessness and Poverty": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/National Law Center on Homelessness and Poverty.png", 
    ".[!": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/.[!.]*", 
    "California Emergency Foodlink": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/California Emergency Foodlink.jpg", 
    "Food Bank of Northeast Georgia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Northeast Georgia.png", 
    "Coalition on Temporary Shelter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Coalition on Temporary Shelter.jpg", 
    "Midwest Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Midwest Food Bank.jpeg", 
    "Mid-Ohio Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Mid-Ohio Foodbank.jpg", 
    "Golden Harvest Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Golden Harvest Food Bank.jpg", 
    "North Kent Connect": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/North Kent Connect.jpg", 
    "Food Bank of North Central Arkansas": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of North Central Arkansas.jpg", 
    "Cross Roads House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Cross Roads House.jpg", 
    "HEARTH": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/HEARTH.jpg", 
    "Second Harvest Food Bank of Orange County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Orange County.png", 
    "Tender Mercies": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Tender Mercies.png", 
    "Visalia Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Visalia Rescue Mission.jpg", 
    "MANNA FoodBank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/MANNA FoodBank.jpg", 
    "Foodlink": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Foodlink.jpg", 
    "Mission SOLANO": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Mission SOLANO.jpg", 
    "New England Center and Home for Veterans": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/New England Center and Home for Veterans.svg", 
    "Akron-Canton Regional Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Akron-Canton Regional Foodbank.jpg", 
    "Food Finders": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Finders.jpg", 
    "Brazos Valley Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Brazos Valley Food Bank.jpeg", 
    "Las Vegas Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Las Vegas Rescue Mission.jpg", 
    "The Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Gospel Mission.png", 
    "Stewpot Community Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Stewpot Community Services.jpg", 
    "Second Harvest Food Bank Santa Cruz County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank Santa Cruz County.jpg", 
    "Broad Street Ministry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Broad Street Ministry.jpg", 
    "Homeless Empowerment Program": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Homeless Empowerment Program.png", 
    "Christian HELP Foundation": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Christian HELP Foundation.jpg", 
    "The Road Home": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Road Home.jpg", 
    "Food Bank of Northern Indiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Northern Indiana.jpeg", 
    "Montgomery Area Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Montgomery Area Food Bank.png", 
    "Raleigh Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Raleigh Rescue Mission.jpg", 
    " Indiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Indiana.png", 
    "Good Shepherd Food Bank of Maine": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Good Shepherd Food Bank of Maine.jpg", 
    "Bread of Life Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bread of Life Mission.jpg", 
    "Sunnyvale Community Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sunnyvale Community Services.GIF", 
    "Arlington Street People's Assistance Network": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Arlington Street People's Assistance Network.png", 
    "Second Harvest Foodbank of the Mahoning Valley": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Foodbank of the Mahoning Valley.png", 
    "Homeless Solutions": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Homeless Solutions.jpg", 
    "Missoula Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Missoula Food Bank.jpg", 
    "Inspiration Corporation": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Inspiration Corporation.jpg", 
    "Loaves & Fishes Community Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Loaves & Fishes Community Services.jpg", 
    "Miami Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Miami Rescue Mission.jpg", 
    "Second Harvest Food Bank of Northeast Tennessee": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Northeast Tennessee.jpg", 
    "Olympia Union Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Olympia Union Gospel Mission.jpg", 
    "Manna on Main Street": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Manna on Main Street.jpg", 
    "Second Harvest Food Bank of Central Florida": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Central Florida.jpg", 
    "Montana Food Bank Network": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Montana Food Bank Network.png", 
    "Richmond Friends of the Homeless Ltd": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Richmond Friends of the Homeless Ltd.jpg", 
    "Dare to Care Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Dare to Care Food Bank.jpg", 
    "Nashville Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Nashville Rescue Mission.jpg", 
    "The Lord's Place": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Lord's Place.jpg", 
    "Clark County Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Clark County Food Bank.png", 
    " Georgia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Georgia.jpg", 
    "HIDDEN HARVEST": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/HIDDEN HARVEST.jpg", 
    "Cityteam": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Cityteam.jpg", 
    "Lazarus House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Lazarus House.jpg", 
    "Northampton Survival Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Northampton Survival Center.png", 
    "Bread of the Mighty Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bread of the Mighty Food Bank.png", 
    "CARITAS": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/CARITAS.png", 
    "Arkansas Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Arkansas Foodbank.png", 
    "Atlantic City Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Atlantic City Rescue Mission.jpg", 
    "Denver Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Denver Rescue Mission.jpg", 
    "LifeMoves": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/LifeMoves.jpg", 
    "Sunshine Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sunshine Ministries.jpeg", 
    "St. Mary's Food Bank Alliance": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/St. Mary's Food Bank Alliance.jpg", 
    "Second Harvest Community Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Community Food Bank.jpg", 
    "Allentown Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Allentown Rescue Mission.jpg", 
    "Muncie Mission Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Muncie Mission Ministries.jpg", 
    "Feeding the Gulf Coast": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding the Gulf Coast.jpg", 
    "St. Patrick Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/St. Patrick Center.png", 
    "University District Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/University District Food Bank.jpg", 
    "The Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Foodbank.svg", 
    "Atlanta Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Atlanta Mission.jpg", 
    "Rosie's Place": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rosie's Place.png", 
    "United Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/United Food Bank.jpg", 
    "Frederick Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Frederick Rescue Mission.svg", 
    "Alameda County Community Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Alameda County Community Food Bank.jpg", 
    "Treasure Coast Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Treasure Coast Food Bank.png", 
    "Foodshare": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Foodshare.png", 
    "Metropolitan Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Metropolitan Ministries.png", 
    "Preble Street": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Preble Street.jpg", 
    "Share Our Selves": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Share Our Selves.jpg", 
    "Springs Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Springs Rescue Mission.jpg", 
    "Providence House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Providence House.jpg", 
    "Gleaners Food Bank of Indiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Gleaners Food Bank of Indiana.jpg", 
    "Table to Table": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Table to Table.jpg", 
    " Omaha": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Omaha.jpg", 
    "Three Square": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Three Square.jpg", 
    "Kokomo Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Kokomo Rescue Mission.jpg", 
    "On The Rise": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/On The Rise.jpeg", 
    ".": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/..?*", 
    "St. John Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/St. John Center.jpg", 
    "Second Harvest Food Bank of East Central Indiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of East Central Indiana.jpg", 
    "Erie City Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Erie City Mission.jpg", 
    "Weld Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Weld Food Bank.jpg", 
    "Upper Valley Haven": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Upper Valley Haven.jpg", 
    "Rescue Mission of Trenton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rescue Mission of Trenton.jpg", 
    "Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rescue Mission.svg", 
    "Food Bank of the Rio Grande Valley": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of the Rio Grande Valley.jpg", 
    "Worcester County Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Worcester County Food Bank.jpg", 
    "City Rescue Mission of Lansing": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/City Rescue Mission of Lansing.png", 
    "Wichita Falls Faith Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Wichita Falls Faith Mission.jpg", 
    "Shared Harvest Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Shared Harvest Foodbank.jpg", 
    "Arvada Community Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Arvada Community Food Bank.jpg", 
    "Atlanta Community Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Atlanta Community Food Bank.jpg", 
    "North Texas Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/North Texas Food Bank.jpg", 
    "Wayside Christian Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Wayside Christian Mission.png", 
    "Wellspring House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Wellspring House.jpg", 
    "Family Gateway": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Family Gateway.jpg", 
    "Massachusetts Coalition for the Homeless": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Massachusetts Coalition for the Homeless.jpg", 
    "Solutions for Change": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Solutions for Change.png", 
    "Homes With Hope": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Homes With Hope.jpg", 
    "The Urban Ministry Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Urban Ministry Center.png", 
    "West Texas Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/West Texas Food Bank.jpg", 
    "Hope Helps": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hope Helps.jpg", 
    "Shelter Partnership": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Shelter Partnership.png", 
    "Central Pennsylvania Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Central Pennsylvania Food Bank.jpg", 
    "Second Harvest Food Bank of Santa Clara and San Mateo Counties": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Santa Clara and San Mateo Counties.jpg", 
    "Crossroads Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Crossroads Center.jpg", 
    "Food Bank of Western New York": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Western New York.png", 
    "Jacobs & Cushman San Diego Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Jacobs & Cushman San Diego Food Bank.jpg", 
    "The Food Bank of Central Louisiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Food Bank of Central Louisiana.jpg", 
    "San Diego Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/San Diego Rescue Mission.jpg", 
    "America's Second Harvest of the Big Bend": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/America's Second Harvest of the Big Bend.png", 
    "Feeding South Dakota": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding South Dakota.png", 
    "Boulder Shelter for the Homeless": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Boulder Shelter for the Homeless.png", 
    "Christian Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Christian Services.png", 
    "Lexington Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Lexington Rescue Mission.jpg", 
    "Bethesda Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bethesda Mission.jpg", 
    "Latern House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Latern House.jpg", 
    "The Night Ministry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Night Ministry.jpg", 
    "Providence Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Providence Rescue Mission.jpg", 
    "Northwest Harvest": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Northwest Harvest.jpg", 
    "Breakthrough Urban Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Breakthrough Urban Ministries.jpg", 
    "Christian Service Center for Central Florida": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Christian Service Center for Central Florida.jpg", 
    "Food Pantry of Waukesha County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Pantry of Waukesha County.jpg", 
    "Toledo Northwestern Ohio Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Toledo Northwestern Ohio Food Bank.jpg", 
    "Linn Benton Food Share": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Linn Benton Food Share.jpg", 
    "Foodbank of Santa Barbara County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Foodbank of Santa Barbara County.jpg", 
    "Fredericksburg Area Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Fredericksburg Area Food Bank.png", 
    "Children's Restoration Network": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Children's Restoration Network.png", 
    "FACETS": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/FACETS.jpg", 
    "ACCESS": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ACCESS.png", 
    " Arkansas": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Arkansas.jpg", 
    "Food for Lane County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food for Lane County.png", 
    "Food Bank of Corpus Christi": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Corpus Christi.jpg", 
    "High Plains Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/High Plains Food Bank.jpg", 
    "Solid Ground": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Solid Ground.gif", 
    "The San Francisco-Marin Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The San Francisco-Marin Food Bank.png", 
    "Eastside Community Ministry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Eastside Community Ministry.jpg", 
    "Crossroads Nogales Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Crossroads Nogales Mission.JPG", 
    "Hope Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hope Gospel Mission.jpg", 
    "Miracle Hill Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Miracle Hill Ministries.jpg", 
    "Homeless Family Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Homeless Family Center.jpg", 
    "The Gathering Place": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Gathering Place.jpg", 
    "North Country Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/North Country Food Bank.jpg", 
    "SafeHouse Outreach": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/SafeHouse Outreach.png", 
    "Feeding America West Michigan Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding America West Michigan Food Bank.png", 
    "Emergency Food Network": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Emergency Food Network.jpg", 
    "Camillus House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Camillus House.jpg", 
    "North Helpline": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/North Helpline.jpeg", 
    "Imperial Valley Food Pantry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Imperial Valley Food Pantry.jpg", 
    "Samaritan Ministry of Greater Washington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Samaritan Ministry of Greater Washington.png", 
    "Community Soup Kitchen and Outreach Center Inc": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community Soup Kitchen and Outreach Center Inc.png", 
    "Building Changes": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Building Changes.jpg", 
    "Faith Mission of Elkhart": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Faith Mission of Elkhart.png", 
    "Coachella Valley Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Coachella Valley Rescue Mission.jpg", 
    "Central Iowa Shelter & Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Central Iowa Shelter & Services.png", 
    "The Light House Mission Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Light House Mission Ministries.jpg", 
    "My Friend's Place": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/My Friend's Place.jpg", 
    "Gleaners Community Food Bank of Southeastern Michigan": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Gleaners Community Food Bank of Southeastern Michigan.jpg", 
    "Northeast Iowa Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Northeast Iowa Food Bank.jpg", 
    "Topeka Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Topeka Rescue Mission.JPG", 
    "Food Gatherers": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Gatherers.png", 
    "Anne Arundel County Food Bank Inc": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Anne Arundel County Food Bank Inc.jpg", 
    "Family Emergency Shelter Coalition": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Family Emergency Shelter Coalition.png", 
    "Goodwill Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Goodwill Rescue Mission.jpg", 
    "Second Harvest Food Bank of Northwest North Carolina": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Northwest North Carolina.jpg", 
    "Martha's Village and Kitchen": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Martha's Village and Kitchen.png", 
    " Los Angeles": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Los Angeles.jpg", 
    "Union Gospel Mission Twin Cities": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Union Gospel Mission Twin Cities.jpg", 
    "Interfaith Family Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Interfaith Family Services.jpg", 
    "Fulfill": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Fulfill.jpg", 
    "Chrysalis": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Chrysalis.jpg", 
    "City Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/City Mission.jpg", 
    "Vogel Alcove": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Vogel Alcove.jpg", 
    "Community Food Share": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community Food Share.gif", 
    "The Samaritan Inn": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Samaritan Inn.jpg", 
    "Good News Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Good News Rescue Mission.jpg", 
    "The Shade Tree": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Shade Tree.jpg", 
    "Marian House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Marian House.jpg", 
    "Modesto Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Modesto Gospel Mission.jpg", 
    "Phoenix Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Phoenix Rescue Mission.jpg", 
    "Haven of Rest Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Haven of Rest Ministries.jpg", 
    "Tulsa Day Center for the Homeless": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Tulsa Day Center for the Homeless.jpg", 
    "The Mission at Kern County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Mission at Kern County.png", 
    "Central Union Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Central Union Mission.png", 
    " Oklahoma City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Oklahoma City.jpeg", 
    "Durham Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Durham Rescue Mission.jpg", 
    "Harry Chapin Food Bank of Southwest Florida": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Harry Chapin Food Bank of Southwest Florida.png", 
    "Union Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Union Rescue Mission.png", 
    "Daniel Pitino Shelter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Daniel Pitino Shelter.jpg", 
    "Food Bank for Monterey County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank for Monterey County.png", 
    "Bean's Cafe": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Bean's Cafe.jpg", 
    "Carpenter's Shelter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Carpenter's Shelter.jpg", 
    "Center for the Homeless": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Center for the Homeless.jpg", 
    "Syracuse": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Syracuse.jpg", 
    "Pacific House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Pacific House.jpg", 
    "WINGS Program": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/WINGS Program.png", 
    "Facing Hunger": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Facing Hunger.jpg", 
    "River Food Pantry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/River Food Pantry.png", 
    "Kansas City Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Kansas City Rescue Mission.jpg", 
    "Sunday Breakfast Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Sunday Breakfast Mission.jpg", 
    "Food for People": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food for People.jpeg", 
    "Helping Up Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Helping Up Mission.jpg", 
    "Loudoun Hunger Relief": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Loudoun Hunger Relief.jpg", 
    "Raphael House of San Francisco": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Raphael House of San Francisco.jpg", 
    "Second Harvest Food Bank of Middle Tennessee": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Middle Tennessee.jpg", 
    "The Open Door Shelter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Open Door Shelter.jpg", 
    "Homeward Bound of Marin": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Homeward Bound of Marin.svg", 
    "River Bend Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/River Bend Foodbank.jpg", 
    "Cherry Street Mission Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Cherry Street Mission Ministries.png", 
    "Father Woody's Haven of Hope": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Father Woody's Haven of Hope.JPG", 
    "Second Harvest Inland Northwest": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Inland Northwest.jpg", 
    "Family Promise": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Family Promise.jpg", 
    " Louisiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Louisiana.png", 
    "Samaritan Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Samaritan Ministries.png", 
    "The Lamb Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Lamb Center.jpg", 
    "Community Food Bank of Eastern Oklahoma": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community Food Bank of Eastern Oklahoma.png", 
    "Union Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Union Mission.png", 
    "Men's Shelter of Charlotte": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Men's Shelter of Charlotte.png", 
    "Rockford Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rockford Rescue Mission.jpg", 
    "Jimmie Hale Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Jimmie Hale Mission.JPG", 
    "City Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/City Rescue Mission.jpg", 
    "Grace Centers of Hope": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Grace Centers of Hope.jpg", 
    "Union Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Union Gospel Mission.png", 
    "The Midnight Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Midnight Mission.jpg", 
    "Matt Talbot Kitchen & Outreach": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Matt Talbot Kitchen & Outreach.jpg", 
    "The Food Bank for Central & Northeast Missouri": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Food Bank for Central & Northeast Missouri.jpg", 
    "The Foodbank of Southern California": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Foodbank of Southern California.jpeg", 
    "Feeding America Southwest Virginia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Feeding America Southwest Virginia.jpg", 
    "The Food Group": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Food Group.png", 
    "Thrive DC": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Thrive DC.png", 
    "Rescue Mission of El Paso": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rescue Mission of El Paso.jpg", 
    "Fresno Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Fresno Rescue Mission.png", 
    "Greater Baton Rouge Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Greater Baton Rouge Food Bank.jpg", 
    " Houston": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Houston.jpg", 
    "Good Samaritan Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Good Samaritan Ministries.jpg", 
    "Maui Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Maui Food Bank.jpg", 
    "City of Refuge": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/City of Refuge.png", 
    "Lowcountry Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Lowcountry Food Bank.jpg", 
    "Restoration Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Restoration Ministries.jpg", 
    "Together Omaha": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Together Omaha.jpg", 
    "Second Harvest Food Bank of Greater New Orleans and Acadiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Second Harvest Food Bank of Greater New Orleans and Acadiana.jpeg", 
    "Food Bank of Central & Eastern North Carolina": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Central & Eastern North Carolina.jpg", 
    "One Family": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/One Family.jpg", 
    "Food Bank of Northwest Louisiana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Northwest Louisiana.png", 
    "Haven of Rest Rescue Mission of Bristol": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Haven of Rest Rescue Mission of Bristol.jpg", 
    " Little Rock": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Little Rock.jpg", 
    "Water Street Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Water Street Ministries.png", 
    "Food Bank of El Dorado County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of El Dorado County.jpg", 
    "Mid America Assistance Coalition": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Mid America Assistance Coalition.jpg", 
    "Neighborhood Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Neighborhood Ministries.jpg", 
    "The Institute for Human Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Institute for Human Services.png", 
    "Food Bank of Contra Costa and Solano": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Contra Costa and Solano.png", 
    "Gospel Rescue Mission of Grants Pass": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Gospel Rescue Mission of Grants Pass.jpg", 
    "Food Bank of Siouxland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of Siouxland.jpg", 
    "Downtown Women's Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Downtown Women's Center.jpg", 
    "Kandiyohi County Food Shelf": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Kandiyohi County Food Shelf.jpg", 
    "Middle Georgia Community Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Middle Georgia Community Food Bank.jpg", 
    "Salina Rescue Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Salina Rescue Mission.jpg", 
    "Adopt-A-Family": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Adopt-A-Family.jpg", 
    "Rainbow Village": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Rainbow Village.jpg", 
    "Operation Nightwatch": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Operation Nightwatch.png", 
    "Community Enrichment Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Community Enrichment Center.jpg", 
    "Birch Community Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Birch Community Services.png", 
    "Forgotten Harvest": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Forgotten Harvest.jpg", 
    "The Rescue Mission of Salt Lake": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/The Rescue Mission of Salt Lake.jpg", 
    "Philabundance": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Philabundance.jpg", 
    "United Methodist Open Door": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/United Methodist Open Door.jpg", 
    "Vision House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Vision House.jpg", 
    "William Temple House": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/William Temple House.jpg", 
    "Food Bank for Larimer County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank for Larimer County.jpg", 
    "Buffalo City Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Buffalo City Mission.png", 
    "Hawaii Foodbank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Hawaii Foodbank.png", 
    "Fairbanks Community Food Bank Service": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Fairbanks Community Food Bank Service.jpg", 
    "Mel Trotter Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Mel Trotter Ministries.png", 
    "Helena Food Share": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Helena Food Share.png", 
    "Turning Points": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Turning Points.png", 
    "Union Gospel Mission of Grays Harbor": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Union Gospel Mission of Grays Harbor.jpg", 
    "FreeStore FoodBank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/FreeStore FoodBank.jpg", 
    "Yad Ezra": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Yad Ezra.png", 
    " Fort Wayne": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/ Fort Wayne.jpg", 
    "Urban Ministries of Durham": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Urban Ministries of Durham.jpg", 
    "Connecticut Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Connecticut Food Bank.jpg", 
    "Detroit Rescue Mission Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Detroit Rescue Mission Ministries.jpg", 
    "Food Bank for the Heartland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank for the Heartland.jpg", 
    "MorningStar Mission Ministries": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/MorningStar Mission Ministries.jpg", 
    "Harbor Interfaith Services": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Harbor Interfaith Services.jpg", 
    "Manna Food Center": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Manna Food Center.jpg", 
    "Food Bank of West Central Texas": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Food Bank of West Central Texas.jpg", 
    "Redwood Gospel Mission": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/Redwood Gospel Mission.jpg", 
    "SeaGate Food Bank": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/charities/SeaGate Food Bank.jpg"
}