export const cityImages = {
    "Lockland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lockland.jpg", 
    "Toledo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Toledo.png", 
    "Renton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Renton.jpeg", 
    "Columbia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Columbia.png", 
    "Verona": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Verona.jpg", 
    "Fairfax": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fairfax.jpg", 
    "Fremont": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fremont.jpg", 
    "El Paso": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/El Paso.jpg", 
    "Atlanta": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Atlanta.ashx", 
    "Overtown": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Overtown.jpg", 
    "Bradenton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bradenton.png", 
    "Holland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Holland.jpg", 
    "Lakeland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lakeland.png", 
    "Redding": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Redding.jpg", 
    "Exeter": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Exeter.jpg", 
    "Charlotte": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Charlotte.jpeg", 
    "Moseley": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Moseley.jpg", 
    "Frisco": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Frisco.png", 
    "Seattle": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Seattle.ashx", 
    "Santa Barbara": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Santa Barbara.jpg", 
    "Allentown": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Allentown.jpg", 
    "Denver": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Denver.jpg", 
    "Burlington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Burlington.jpg", 
    "San Diego": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/San Diego.jpg", 
    "Waukegan": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Waukegan.jpg", 
    "Boise": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Boise.jpg", 
    "Honolulu": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Honolulu.jpg", 
    "Colorado Springs": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Colorado Springs.jpg", 
    "Missoula": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Missoula.jpg", 
    "Youngstown": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Youngstown.jpg", 
    "Sunnyvale": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Sunnyvale.jpg", 
    "Northampton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Northampton.png", 
    "Hatfield": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hatfield.jpg", 
    "Terre Haute": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Terre Haute.jpg", 
    "Delmont": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Delmont.jpeg", 
    "Las Vegas": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Las Vegas.jpg", 
    "Harvey": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Harvey.jpg", 
    "Lansing": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lansing.jpg", 
    "Richmond": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Richmond.jpg", 
    "Providence": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Providence.jpg", 
    "Clearwater": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Clearwater.jpg", 
    "Pasadena": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Pasadena.jpg", 
    "Norfork": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Norfork.jpg", 
    "Columbus": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Columbus.jpg", 
    "Indianapolis": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Indianapolis.jpg", 
    "Sarasota": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Sarasota.jpg", 
    "South Bend": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/South Bend.jpg", 
    "Watsonville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Watsonville.jpg", 
    "Lewisville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lewisville.jpg", 
    "Akron": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Akron.png", 
    "Memphis": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Memphis.jpg", 
    "Elizabeth City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Elizabeth City.JPG", 
    "Orlando": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Orlando.jpg", 
    "Morris Plains": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Morris Plains.jpg", 
    "Wheaton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Wheaton.png", 
    "Oxnard": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Oxnard.jpg", 
    "Costa Mesa": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Costa Mesa.jpg", 
    "Birmingham": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Birmingham.jpg", 
    "Oklahoma City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Oklahoma City.jpeg", 
    "Hattiesburg": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hattiesburg.jpg", 
    "West Palm Beach": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/West Palm Beach.jpg", 
    "Nogales": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Nogales.jpg", 
    "Waterloo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Waterloo.jpg", 
    "Phoenix": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Phoenix.gif", 
    "Irvine": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Irvine.jpg", 
    "Clayton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Clayton.jpeg", 
    "Middleton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Middleton.jpg", 
    "Joliet": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Joliet.jpg", 
    "Sioux Falls": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Sioux Falls.jpg", 
    "Chattanooga": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Chattanooga.jpg", 
    "Duluth": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Duluth.jpg", 
    "Oak Park": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Oak Park.jpg", 
    "St. Louis": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/St. Louis.jpg", 
    "Tallahassee": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Tallahassee.jpg", 
    "Lakewood": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lakewood.jpg", 
    "Crookston": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Crookston.jpg", 
    "Cameron Park": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Cameron Park.jpg", 
    "Longview": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Longview.jpg", 
    "Salinas": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Salinas.jpg", 
    "Salisbury": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Salisbury.png", 
    "Schenectady": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Schenectady.jpg", 
    "Monroe": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Monroe.jpg", 
    "Silver Spring": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Silver Spring.jpeg", 
    "Crownsville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Crownsville.png", 
    "Arlington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Arlington.jpg", 
    "Montgomery": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Montgomery.jpg", 
    "Newark": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Newark.jpg", 
    "Covington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Covington.jpg", 
    "Brunswick": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Brunswick.jpg", 
    "Zanesville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Zanesville.jpg", 
    "Fort Wayne": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fort Wayne.jpg", 
    "Valley Park": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Valley Park.jpg", 
    "Leesburg": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Leesburg.jpg", 
    "Norfolk": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Norfolk.png", 
    "Miami": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Miami.jpg", 
    "Lorain": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lorain.jpg", 
    "Augusta": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Augusta.jpg", 
    "Topeka": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Topeka.png", 
    "Indio": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Indio.jpeg", 
    "Savannah": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Savannah.jpg", 
    "Sikeston": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Sikeston.jpg", 
    "Pharr": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Pharr.jpg", 
    "Fort Worth": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fort Worth.jpg", 
    "Gary": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Gary.jpg", 
    "Kalispell": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Kalispell.jpg", 
    "Washington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Washington.png", 
    "Glanshaw": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Glanshaw.jpg", 
    "Reading": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Reading.jpg", 
    "Lansdale": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lansdale.jpeg", 
    "Hayward": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hayward.jpg", 
    "Elizabeth": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Elizabeth.jpg", 
    "Everett": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Everett.jpg", 
    "Williamsport": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Williamsport.jpg", 
    "Salt Lake City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Salt Lake City.jpg", 
    "Neptune": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Neptune.jpg", 
    "Tucson": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Tucson.jpg", 
    "St. Louis Park": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/St. Louis Park.jpeg", 
    "Buffalo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Buffalo.jpg", 
    "Cambridge": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Cambridge.jpg", 
    "Boston": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Boston.jpg", 
    "Lawrence": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lawrence.jpg", 
    "Owensboro": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Owensboro.png", 
    "Huntington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Huntington.jpg", 
    "Erie": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Erie.png", 
    "Hauppauge": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hauppauge.jpg", 
    "Norwalk": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Norwalk.jpg", 
    "Jackson": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Jackson.png", 
    "Elkhart": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Elkhart.png", 
    "Comstock Park": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Comstock Park.jpg", 
    "Elmsford": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Elmsford.gif", 
    "Great Falls": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Great Falls.png", 
    "Mesa": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Mesa.jpg", 
    "Lincoln": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lincoln.jpg", 
    "Shreveport": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Shreveport.jpg", 
    "Rockville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Rockville.jpg", 
    "Bethel Heights": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bethel Heights.jpeg", 
    "Hagerstown": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hagerstown.jpg", 
    "Summit": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Summit.png", 
    "Charleston": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Charleston.jpg", 
    "Hastings": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hastings.jpg", 
    "Kalamazoo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Kalamazoo.jpg", 
    "Vero Beach": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Vero Beach.jpg", 
    "Wichita Falls": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Wichita Falls.png", 
    "Concord": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Concord.jpg", 
    "Kokomo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Kokomo.jpg", 
    "Auburn": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Auburn.png", 
    "Hillside": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hillside.jpg", 
    "New York": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/New York.jpg", 
    "Pembroke Park": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Pembroke Park.jpg", 
    "Abilene": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Abilene.webp", 
    "Lubbock": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lubbock.jpg", 
    "New Hope": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/New Hope.jpg", 
    "Philadelphia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Philadelphia.jpg", 
    "Bainbridge Island": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bainbridge Island.jpg", 
    "Westport": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Westport.jpg", 
    "Woodridge": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Woodridge.jpg", 
    "Fort Myers": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fort Myers.jpg", 
    "Odessa": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Odessa.jpg", 
    "Louisville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Louisville.jpg", 
    "Grand Rapids": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Grand Rapids.jpg", 
    "Paso Robles": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Paso Robles.jpg", 
    "Decatur": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Decatur.jpg", 
    "Lynn": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lynn.jpg", 
    "Elk Grove": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Elk Grove.jpg", 
    "Ogden": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Ogden.jpg", 
    "Frederick": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Frederick.jpg", 
    "Lafayette": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lafayette.png", 
    "Trenton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Trenton.jpg", 
    "Corpus Christi": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Corpus Christi.svg", 
    "Farmers Branch": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Farmers Branch.png", 
    "Ypsilanti": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Ypsilanti.jpg", 
    ".[!": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/.[!.]*", 
    "Morristown": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Morristown.jpg", 
    "Barre": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Barre.jpg", 
    "Tulsa": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Tulsa.jpg", 
    "Theodore": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Theodore.jpg", 
    "Sacramento": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Sacramento.jpg", 
    "Ann Arbor": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Ann Arbor.jpg", 
    "York": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/York.jpg", 
    "Saginaw": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Saginaw.jpg", 
    "Lexington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lexington.gif", 
    "Wailuku": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Wailuku.jpg", 
    "Gloucester": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Gloucester.jpg", 
    "Olympia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Olympia.png", 
    "Fredericksburg": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fredericksburg.jpg", 
    "Minneapolis": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Minneapolis.jpg", 
    "Visalia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Visalia.jpg", 
    "Manchester": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Manchester.jpg", 
    "El Centro": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/El Centro.svg", 
    "Rochester": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Rochester.jpg", 
    "Grove City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Grove City.jpg", 
    "Knoxville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Knoxville.jpg", 
    "Arvada": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Arvada.jpg", 
    "Rapid City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Rapid City.jpg", 
    "Anderson": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Anderson.jpg", 
    "Grand Forks": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Grand Forks.jpg", 
    "San Francisco": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/San Francisco.png", 
    "Mckinney": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Mckinney.jpg", 
    "Appleton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Appleton.jpg", 
    "Pontiac": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Pontiac.jpg", 
    "Hempstead": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hempstead.jpg", 
    "Aurora": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Aurora.jpg", 
    "New Orleans": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/New Orleans.jpg", 
    "Los Angeles": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Los Angeles.jpg", 
    "Grants Pass": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Grants Pass.png", 
    "San Antonio": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/San Antonio.jpg", 
    "Rockford": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Rockford.png", 
    "Willmar": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Willmar.jpeg", 
    "Bridgeport": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bridgeport.jpg", 
    "Tustin": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Tustin.jpg", 
    "San Pedro": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/San Pedro.jpg", 
    "Bronx": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bronx.jpg", 
    "Portsmouth": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Portsmouth.jpg", 
    "Santa Fe": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Santa Fe.jpg", 
    "Modesto": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Modesto.jpg", 
    "Tacoma": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Tacoma.jpg", 
    "Aberdeen": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Aberdeen.jpg", 
    "Fairbanks": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fairbanks.jpg", 
    "Cary": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Cary.jpg", 
    "Johnson City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Johnson City.jpg", 
    "Chicago": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Chicago.jpg", 
    "White River Junction": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/White River Junction.jpg", 
    "Asheville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Asheville.jpg", 
    "Marietta": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Marietta.jpg", 
    "Saint Louis": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Saint Louis.jpg", 
    "Davenport": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Davenport.jpg", 
    "Bethpage": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bethpage.JPG", 
    "Salem": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Salem.jpg", 
    "Saint Joseph": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Saint Joseph.jpg", 
    "Cleveland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Cleveland.jpg", 
    "White Bear Lake": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/White Bear Lake.png", 
    "Huntsville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Huntsville.jpg", 
    "Nashville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Nashville.jpeg", 
    "Amarillo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Amarillo.jpg", 
    "Harrisburg": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Harrisburg.jpg", 
    "Fort Pierce": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fort Pierce.png", 
    "Waukesha": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Waukesha.jpg", 
    "Anchorage": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Anchorage.jpg", 
    "Kansas City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Kansas City.jpg", 
    "Raleigh": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Raleigh.jpg", 
    "Bristol": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bristol.jpg", 
    "Eureka": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Eureka.jpg", 
    "Houston": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Houston.jpg", 
    "Hampton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Hampton.jpg", 
    "Wallingford": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Wallingford.jpg", 
    "Des Moines": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Des Moines.jpg", 
    "Milwaukee": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Milwaukee.jpg", 
    "Portland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Portland.jpg", 
    "St. Paul": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/St. Paul.jpg", 
    "Roanoke": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Roanoke.png", 
    "Dayton": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Dayton.jpg", 
    "Tyler": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Tyler.jpg", 
    "Santa Rosa": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Santa Rosa.jpeg", 
    "Bloomington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bloomington.jpg", 
    "Victoria": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Victoria.jpg", 
    "Flint": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Flint.jpg", 
    "Tampa": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Tampa.jpg", 
    "Menlo Park": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Menlo Park.jpg", 
    "Big Island": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Big Island.jpg", 
    "Winston-Salem": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Winston-Salem.jpg", 
    "Cincinnati": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Cincinnati.jpg", 
    "Plant City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Plant City.jpg", 
    "Waltham": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Waltham.ashx", 
    "Alexandria": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Alexandria.jpg", 
    "Texarkana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Texarkana.jpg", 
    "Fresno": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fresno.png", 
    "Kingsport": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Kingsport.png", 
    "Bloomfield": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bloomfield.jpeg", 
    "Long Beach": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Long Beach.jpg", 
    "Durham": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Durham.jpg", 
    "Shrewsbury": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Shrewsbury.jpg", 
    "Naperville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Naperville.jpg", 
    "Warren": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Warren.jpg", 
    "Bakersfield": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bakersfield.jpg", 
    "Gainesville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Gainesville.jpg", 
    "Palatine": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Palatine.jpg", 
    "Muncie": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Muncie.jpg", 
    "Eugene": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Eugene.jpg", 
    "Casselberry": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Casselberry.jpg", 
    "Glen Ellyn": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Glen Ellyn.jpg", 
    " Miami": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/ Miami.jpg", 
    "Albuquerque": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Albuquerque.jpg", 
    "Sioux City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Sioux City.jpg", 
    "North Richland Hills": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/North Richland Hills.jpg", 
    "Syracuse": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Syracuse.jpg", 
    "Spokane": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Spokane.jpg", 
    "Wilmington": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Wilmington.jpg", 
    "San Jose": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/San Jose.jpg", 
    "High Point": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/High Point.jpg", 
    "Berkley": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Berkley.jpg", 
    "Panama City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Panama City.jpg", 
    "Macon": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Macon.jpg", 
    "Oviedo": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Oviedo.jpg", 
    "Madison": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Madison.jpg", 
    "Duquesne": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Duquesne.png", 
    "Fort Collins": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fort Collins.jpg", 
    "Atlantic City": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Atlantic City.jpg", 
    "Pasco": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Pasco.jpeg", 
    "Salina": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Salina.jpg", 
    "Dallas": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Dallas.ashx", 
    "Urbana": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Urbana.jpg", 
    "Greenville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Greenville.jpg", 
    "Fairfield": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Fairfield.jpg", 
    "Corvallis": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Corvallis.jpg", 
    ".": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/..?*", 
    "Boulder": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Boulder.jpg", 
    "Normal": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Normal.jpg", 
    "Baton Rouge": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Baton Rouge.png", 
    "Pennsauken": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Pennsauken.jpg", 
    "Lake Worth": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lake Worth.jpg", 
    "Billings": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Billings.jpg", 
    "Bryan": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Bryan.jpeg", 
    "Maryville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Maryville.jpg", 
    "Little Rock": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Little Rock.jpg", 
    "Detroit": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Detroit.ashx", 
    "Englewood Cliffs": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Englewood Cliffs.gif", 
    "Austin": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Austin.jpg", 
    "Greensboro": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Greensboro.jpg", 
    "Lawrenceville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lawrenceville.jpg", 
    "Greeley": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Greeley.jpg", 
    "Helena": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Helena.jpg", 
    "Gaithersburg": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Gaithersburg.jpg", 
    "Lancaster": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Lancaster.jpg", 
    "Vista": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Vista.jpg", 
    "Pensacola": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Pensacola.jpg", 
    "Vancouver": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Vancouver.jpg", 
    "Springfield": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Springfield.jpg", 
    "Geneva": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Geneva.jpg", 
    "McCarran": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/McCarran.jpg", 
    "Jacksonville": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Jacksonville.jpg", 
    "Omaha": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Omaha.jpg", 
    "Wichita": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Wichita.jpg", 
    "Novato": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Novato.jpg", 
    "Eau Claire": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Eau Claire.jpg", 
    "Baltimore": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Baltimore.jpg", 
    "New Haven": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/New Haven.gif", 
    "Roswell": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Roswell.jpg", 
    "Colonial Heights": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Colonial Heights.jpg", 
    "Pittsburgh": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Pittsburgh.jpg", 
    "Stamford": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Stamford.jpg", 
    "Oakland": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Oakland.jpg", 
    "Peoria": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/cities/Peoria.jpg"
}