export const countyImages = {
    "Monroe County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Monroe County.svg", 
    "Hinds County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hinds County.jpg", 
    "Forsyth County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Forsyth County.jpg", 
    "Escambia County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Escambia County.jpg", 
    "Josephine County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Josephine County.jpg", 
    "Madison County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Madison County.jpg", 
    "Westmoreland County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Westmoreland County.jpg", 
    "Tulsa County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Tulsa County.jpg", 
    "Pasquotank County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Pasquotank County.jpg", 
    ".[!": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/.[!.]*", 
    "Anne Arundel County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Anne Arundel County.jpg", 
    "Milwaukee County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Milwaukee County.jpg", 
    "Adams County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Adams County.jpg", 
    "Contra Costa County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Contra Costa County.png", 
    "Camden County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Camden County.jpg", 
    "Knox County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Knox County.jpg", 
    "Boulder County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Boulder County.jpg", 
    "San Mateo County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/San Mateo County.png", 
    "Grays Harbor County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Grays Harbor County.jpg", 
    "Champaign County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Champaign County.png", 
    "Berks County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Berks County.jpg", 
    "Tarrant County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Tarrant County.png", 
    "Mobile County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Mobile County.jpg", 
    "Fairfield County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Fairfield County.jpg", 
    "Schenectady County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Schenectady County.jpg", 
    "Manatee County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Manatee County.png", 
    "Saline County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Saline County.png", 
    "Vigo County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Vigo County.png", 
    "Monmouth County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Monmouth County.jpg", 
    "Butler County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Butler County.png", 
    "Seminole County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Seminole County.jpg", 
    "Boone County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Boone County.jpg", 
    "New York County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/New York County.jpg", 
    "Gwinnett County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Gwinnett County.png", 
    "San Luis Obispo County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/San Luis Obispo County.jpg", 
    "Benton County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Benton County.png", 
    "Worcester County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Worcester County.png", 
    "Spotsylvania County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Spotsylvania County.jpg", 
    "El Dorado County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/El Dorado County.jpg", 
    "Smith County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Smith County.jpg", 
    "Black Hawk County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Black Hawk County.png", 
    "Augusta County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Augusta County.png", 
    "Maui County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Maui County.jpg", 
    "Broward County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Broward County.svg", 
    "Dauphin County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Dauphin County.jpg", 
    "Buncombe County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Buncombe County.jpg", 
    "Rapides Parish": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Rapides Parish.jpg", 
    "Chesterfield County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Chesterfield County.png", 
    "El Paso County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/El Paso County.png", 
    "Scott County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Scott County.png", 
    "Duval County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Duval County.jpg", 
    "Caddo Parish": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Caddo Parish.jpg", 
    "Outagamie County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Outagamie County.jpg", 
    "Windsor County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Windsor County.jpeg", 
    "Denton County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Denton County.jpg", 
    "St. Louis County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/St. Louis County.jpg", 
    "Denver County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Denver County.jpg", 
    "Howard County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Howard County.jpg", 
    "Forrest County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Forrest County.jpg", 
    "Kent County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Kent County.png", 
    "Kane County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Kane County.png", 
    "Middlesex County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Middlesex County.jpg", 
    "Trumbull County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Trumbull County.png", 
    "Sacramento County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Sacramento County.svg", 
    "Allegheny County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Allegheny County.png", 
    "Mahoning County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Mahoning County.png", 
    "Winnebago County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Winnebago County.jpg", 
    "Sedgwick County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Sedgwick County.jpg", 
    "Jefferson County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Jefferson County.svg", 
    "Hillsborough County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hillsborough County.jpg", 
    "Nueces County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Nueces County.jpg", 
    "Erie County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Erie County.jpg", 
    "Sharkey County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Sharkey County.jpg", 
    "Yellowstone County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Yellowstone County.jpg", 
    "Pulaski County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Pulaski County.jpg", 
    "Fresno County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Fresno County.jpg", 
    "Fairfax County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Fairfax County.jpg", 
    "Anchorage Municipality": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Anchorage Municipality.png", 
    "Anderson County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Anderson County.jpg", 
    "Harris County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Harris County.png", 
    "Bernalillo County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Bernalillo County.png", 
    "Larimer County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Larimer County.jpg", 
    "Palm Beach County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Palm Beach County.gif", 
    "Charleston County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Charleston County.jpg", 
    "Leon County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Leon County.jpg", 
    "Orange County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Orange County.jpg", 
    "Cabell County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Cabell County.png", 
    "Kandiyohi County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Kandiyohi County.jpg", 
    "Rockingham County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Rockingham County.jpg", 
    "Missoula County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Missoula County.png", 
    "King County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/King County.svg", 
    "Marion County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Marion County.png", 
    "Genesee County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Genesee County.jpg", 
    "Essex County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Essex County.jpg", 
    "Colonial Heights city": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Colonial Heights city.png", 
    "Washington County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Washington County.jpg", 
    "Potter County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Potter County.jpg", 
    "Nassau County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Nassau County.jpg", 
    "Alachua County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Alachua County.jpg", 
    "Elkhart County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Elkhart County.png", 
    "Santa Clara County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Santa Clara County.png", 
    "Lake County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lake County.png", 
    "Gregg County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Gregg County.jpg", 
    "York County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/York County.png", 
    "Douglas County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Douglas County.png", 
    "Baxter County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Baxter County.jpg", 
    "Alameda County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Alameda County.png", 
    "Lehigh County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lehigh County.jpg", 
    "Indian River County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Indian River County.png", 
    "Richmond County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Richmond County.jpg", 
    "Cuyahoga County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Cuyahoga County.jpeg", 
    "Minnehaha County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Minnehaha County.jpg", 
    "Fayette County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Fayette County.png", 
    "Lancaster County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lancaster County.jpg", 
    "DeKalb County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/DeKalb County.jpg", 
    "Ouachita Parish": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Ouachita Parish.jpg", 
    "Alexandria city": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Alexandria city.jpg", 
    "Bexar County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Bexar County.jpg", 
    "Flathead County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Flathead County.jpg", 
    "Kalamazoo County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Kalamazoo County.jpg", 
    "Bedford County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Bedford County.jpg", 
    "District of Columbia": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/District of Columbia.svg", 
    "Shelby County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Shelby County.png", 
    "Atlantic County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Atlantic County.png", 
    "Oklahoma County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Oklahoma County.jpg", 
    "Sullivan County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Sullivan County.png", 
    "Pinellas County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Pinellas County.jpg", 
    "Shawnee County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Shawnee County.png", 
    "Wake County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Wake County.png", 
    "Dane County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Dane County.jpg", 
    "Hennepin County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hennepin County.png", 
    "Hampton city": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hampton city.jpg", 
    "Androscoggin County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Androscoggin County.jpg", 
    "Salem city": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Salem city.jpg", 
    "Muskingum County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Muskingum County.jpg", 
    "Weber County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Weber County.jpg", 
    "Santa Fe County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Santa Fe County.jpg", 
    "Onondaga County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Onondaga County.jpg", 
    "Davidson County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Davidson County.jpg", 
    "Lee County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lee County.jpg", 
    "Eau Claire County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Eau Claire County.png", 
    "Marin County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Marin County.jpg", 
    "Waukesha County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Waukesha County.jpg", 
    "Honolulu County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Honolulu County.png", 
    "Roanoke city": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Roanoke city.jpg", 
    "St. Joseph County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/St. Joseph County.jpg", 
    "Victoria County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Victoria County.jpg", 
    "Fulton County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Fulton County.png", 
    "Woodbury County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Woodbury County.jpg", 
    "Santa Cruz County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Santa Cruz County.png", 
    "Ventura County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Ventura County.png", 
    "Delaware County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Delaware County.png", 
    "Travis County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Travis County.jpeg", 
    "Washoe County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Washoe County.png", 
    ".": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/..?*", 
    "Washtenaw County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Washtenaw County.jpg", 
    "Rabun County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Rabun County.jpg", 
    "Franklin County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Franklin County.png", 
    "Will County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Will County.png", 
    "Mercer County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Mercer County.jpg", 
    "Allen County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Allen County.png", 
    "Pima County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Pima County.jpg", 
    "Sarasota County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Sarasota County.jpg", 
    "Bibb County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Bibb County.jpg", 
    "St. Lucie County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/St. Lucie County.jpg", 
    "Snohomish County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Snohomish County.jpg", 
    "Stanislaus County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Stanislaus County.jpg", 
    "Bay County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Bay County.svg", 
    "Rowan County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Rowan County.jpg", 
    "Cumberland County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Cumberland County.jpg", 
    "Kenton County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Kenton County.jpeg", 
    "Pierce County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Pierce County.jpg", 
    "Mecklenburg County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Mecklenburg County.png", 
    "San Diego County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/San Diego County.jpg", 
    "New Haven County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/New Haven County.gif", 
    "Ottawa County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Ottawa County.jpg", 
    "Pennington County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Pennington County.jpg", 
    "New Castle County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/New Castle County.jpg", 
    "Durham County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Durham County.png", 
    "Blount County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Blount County.jpg", 
    "Hampshire County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hampshire County.svg", 
    "Richmond city": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Richmond city.jpg", 
    "Chittenden County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Chittenden County.jpg", 
    "Brazos County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Brazos County.jpg", 
    "Ingham County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Ingham County.png", 
    "Philadelphia County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Philadelphia County.jpg", 
    "Daviess County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Daviess County.svg", 
    "Spokane County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Spokane County.jpg", 
    "Norfolk city": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Norfolk city.jpg", 
    "Montgomery County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Montgomery County.jpeg", 
    "Fairbanks North Star Borough": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Fairbanks North Star Borough.png", 
    "Solano County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Solano County.jpg", 
    "Summit County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Summit County.jpg", 
    "Miller County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Miller County.jpg", 
    "Cobb County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Cobb County.jpg", 
    "Lubbock County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lubbock County.png", 
    "Wayne County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Wayne County.jpg", 
    "Hampden County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hampden County.png", 
    "Humboldt County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Humboldt County.jpg", 
    "Multnomah County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Multnomah County.jpg", 
    "Polk County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Polk County.jpg", 
    "Riverside County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Riverside County.jpg", 
    "Sonoma County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Sonoma County.jpg", 
    "Kanawha County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Kanawha County.jpg", 
    "Loudoun County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Loudoun County.png", 
    "Tippecanoe County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Tippecanoe County.png", 
    "Buchanan County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Buchanan County.png", 
    "Santa Barbara County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Santa Barbara County.jpg", 
    "Monterey County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Monterey County.jpg", 
    "Ramsey County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Ramsey County.png", 
    "Lucas County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lucas County.png", 
    "Ector County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Ector County.jpg", 
    "East Baton Rouge Parish": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/East Baton Rouge Parish.jpg", 
    "Wichita County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Wichita County.png", 
    "Lorain County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lorain County.png", 
    "Taylor County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Taylor County.jpg", 
    "Arlington County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Arlington County.jpg", 
    "Lewis and Clark County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lewis and Clark County.gif", 
    "Jackson County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Jackson County.png", 
    "Saginaw County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Saginaw County.jpg", 
    "Suffolk County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Suffolk County.jpg", 
    "Bronx County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Bronx County.jpg", 
    "Oakland County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Oakland County.jpg", 
    "Frederick County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Frederick County.png", 
    "Hidalgo County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hidalgo County.jpeg", 
    "Ada County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Ada County.jpg", 
    "Chatham County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Chatham County.jpg", 
    "McLean County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/McLean County.jpg", 
    "DuPage County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/DuPage County.jpg", 
    "Hartford County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hartford County.jpg", 
    "Greene County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Greene County.png", 
    "Cascade County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Cascade County.jpg", 
    "Olmsted County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Olmsted County.gif", 
    "Sangamon County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Sangamon County.png", 
    "Providence County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Providence County.jpg", 
    "Lane County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Lane County.png", 
    "Imperial County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Imperial County.jpg", 
    "Guilford County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Guilford County.jpg", 
    "Baltimore city": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Baltimore city.jpg", 
    "Los Angeles County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Los Angeles County.png", 
    "Westchester County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Westchester County.jpg", 
    "Thurston County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Thurston County.png", 
    "Jefferson Parish": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Jefferson Parish.png", 
    "Salt Lake County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Salt Lake County.jpg", 
    "Collin County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Collin County.jpg", 
    "Clark County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Clark County.jpg", 
    "Greenville County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Greenville County.jpg", 
    "Miami-Dade County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Miami-Dade County.png", 
    "Union County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Union County.jpg", 
    "Richland County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Richland County.jpg", 
    "San Francisco County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/San Francisco County.png", 
    "Peoria County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Peoria County.png", 
    "Shasta County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Shasta County.jpg", 
    "Maricopa County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Maricopa County.jpg", 
    "Tulare County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Tulare County.png", 
    "Grand Forks County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Grand Forks County.jpg", 
    "Cook County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Cook County.png", 
    "Dallas County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Dallas County.jpg", 
    "Hamilton County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Hamilton County.png", 
    "Bergen County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Bergen County.jpg", 
    "Kitsap County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Kitsap County.jpg", 
    "Kern County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Kern County.jpg", 
    "New Hanover County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/New Hanover County.jpg", 
    "Weld County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Weld County.jpg", 
    "Morris County": "https://s3.us-east-2.amazonaws.com/fightpoverty.online/images/counties/Morris County.jpg"
}